// Package boilerplate provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package boilerplate

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xWwW7jNhD9FWLao2TZbXrRLQXaIEAOPfRWGAEjjhXGFMmQIyeuoX8vOJLjxFba1PYG",
	"u8CeJIzE4bw37w25gco13lm0FKHcQKzusZH8evnHdXr44DwG0shB6XV60NojlBApaFtDBs957fIUzONS",
	"+9x50s5Kk3unLWGAkkKLXZdtF7q7B6wIugx+C8GFw30UxipoTnP8fhlgyn5bOYWvsqRfagwnlf27Nnij",
	"7fLaLtxh9Ubb5SllR5LUcia0bQPlX2DxCTLQ9tYHV2GMkHHjDBIqGHDCPDtjY/6UcXmIbKENxpsBniZs",
	"OPpjwAWU8EOxE1MxKKl4w9RuIxmCXP8PSrQ6mtD0m2tSsZ7WUC6kiWOQU0gP7SRNJn37W3vPSllhiKxF",
	"mE2mk2kC4jxatgP8PJlOZpCBl3TPfBTxSdZJYuUGaqQDQadgshcnCTIFrxWUcLUNB4ze2dhz/tN0mh6V",
	"s4SWehd6oyteVzzE3iI93//VjZSekb6thz+j0FZwui6Di+nF2TbtPT6yrXUkFq61SuDwSwaxbRoZ1lBC",
	"QGqDjVySkF6L14szIFnHZI0t1/O0uqBBtu/SbkxSdhzlfvftpAZ8yBfsr30/jHCUAEVhdKQ9emokIY0R",
	"NJS85YMZmHcZeBdHOLhUirfex7+L72GfnU0HPeRDiJdKoWIcIhkwNJw8kfPLGaX/rgp5VFhpRMSwwjCq",
	"xSqgJBQWn7jOQ7q32is2WnX/JsBR8q9e4l4G2SBhSMk3I1oQWvFJACXPG8jAyoaPtRTfUXH8qJRe5+nI",
	"rNHm+ExB5j3WDayk0UoSsjkfWx1QJULnX3BgvacZGuzzKXOKeX8ZVl+VMNMU+IAii+2VZHwoSKX4UB8Z",
	"CkP8m9XlY4uRfnVqfdwIP+fFbuyatT/+uxPn7+l3shEhJthCpindW+4TtH8nlRia993mbFDBXSA3aveM",
	"exST7dM6TtQ7tQ0GSiik18VqVkA37/4JAAD//7x+I1v0DQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
