// Package boilerplate provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package boilerplate

// Defines values for FileLinkInfoStatus.
const (
	FileLinkInfoStatusCompleted FileLinkInfoStatus = "completed"
	FileLinkInfoStatusError     FileLinkInfoStatus = "error"
	FileLinkInfoStatusInProcess FileLinkInfoStatus = "in_process"
	FileLinkInfoStatusNew       FileLinkInfoStatus = "new"
)

// API defines model for API.
type API struct {
	Api string `json:"api,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Description *string `json:"description,omitempty"`
	ErrorCode   *int    `json:"error_code,omitempty"`
}

// FileLinkInfo defines model for FileLinkInfo.
type FileLinkInfo struct {
	Link   string             `json:"link,omitempty"`
	Status FileLinkInfoStatus `json:"status,omitempty"`
}

// FileLinkInfoStatus defines model for FileLinkInfo.Status.
type FileLinkInfoStatus string

// Task defines model for Task.
type Task struct {
	FilesLink []FileLinkInfo `json:"filesLink,omitempty"`
	Id        string         `json:"id"`
}

// AddLinkJSONBody defines parameters for AddLink.
type AddLinkJSONBody = []struct {
	Link string `json:"link,omitempty"`
}

// AddLinkJSONRequestBody defines body for AddLink for application/json ContentType.
type AddLinkJSONRequestBody = AddLinkJSONBody
